# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eksecr-cluster  # Choose a unique name for your EKS cluster
  region: us-east-1      # Make sure this matches the AWS_REGION in your Jenkinsfile

nodeGroups:
  - name: ng-1
    instanceType: t3.medium # Choose an appropriate instance type (e.g., t3.medium, t3.large)
    desiredCapacity: 2      # Number of worker nodes
    minSize: 1
    maxSize: 3
    volumeSize: 20          # EBS volume size for each node in GB
    ssh:
      allow: true          # Set to false in production for security
      publicKeyPath: ~/.ssh/id_rsa.pub # Path to your SSH public key for node access (optional but useful for debugging)
